# Generated by Django 6.0.6 on 2026-06-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('person_image_url', models.URLField(help_text='人物照片URL', max_length=500)),
                ('garment_image_url', models.URLField(help_text='服装图片URL', max_length=500)),
                ('garment_category', models.CharField(choices=[('upper', '上装'), ('lower', '下装'), ('dress', '连衣裙'), ('outer', '外套')], default='upper', max_length=20)),
                ('result_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '试衣任务',
                'verbose_name_plural': '试衣任务',
                'db_table': 'tryon_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
