# Generated by Django 6.0.6 on 2026-06-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('prompt', models.TextField(blank=True, help_text='AI 生成提示词')),
                ('negative_prompt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('sketch', '线稿'), ('style', '款式图'), ('fabric', '面料图'), ('moodboard', '灵感板'), ('flatten', '平铺图')], default='style', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='最终图片URL', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('width', models.IntegerField(default=512)),
                ('height', models.IntegerField(default=768)),
                ('tags', models.JSONField(blank=True, default=list, help_text='标签数组')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='AI生成参数等扩展信息')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '设计稿',
                'verbose_name_plural': '设计稿',
                'db_table': 'design_design',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField()),
                ('image_url', models.URLField(max_length=500)),
                ('prompt', models.TextField(blank=True)),
                ('change_note', models.TextField(blank=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='design.design')),
            ],
            options={
                'verbose_name': '设计稿版本',
                'verbose_name_plural': '设计稿版本',
                'db_table': 'design_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['creator', 'status'], name='design_desi_creator_7dde47_idx'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['category'], name='design_desi_categor_cbaa06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designversion',
            unique_together={('design', 'version_number')},
        ),
    ]
