# Generated by Django 6.0.6 on 2026-06-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('style_code', models.CharField(blank=True, help_text='款号', max_length=50)),
                ('category', models.CharField(blank=True, help_text='品类', max_length=50)),
                ('fabric_description', models.TextField(blank=True, help_text='面料说明')),
                ('size_spec', models.JSONField(blank=True, default=dict, help_text='尺码规格表')),
                ('process_steps', models.JSONField(blank=True, default=list, help_text='工序步骤列表')),
                ('tech_drawing_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '审核中'), ('approved', '已批准')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.design')),
            ],
            options={
                'verbose_name': '工艺单',
                'verbose_name_plural': '工艺单',
                'db_table': 'techpack_techpack',
                'ordering': ['-created_at'],
            },
        ),
    ]
