# Generated by Django 6.0.6 on 2026-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(db_index=True, max_length=50)),
                ('worker_name', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('style_code', models.CharField(blank=True, max_length=50)),
                ('process_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(help_text='完成数量')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='单价', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='合计', max_digits=10)),
                ('source', models.CharField(default='manual', max_length=20)),
            ],
            options={
                'verbose_name': '工资记录',
                'verbose_name_plural': '工资记录',
                'db_table': 'wages_record',
                'ordering': ['-date', 'worker_id'],
                'indexes': [models.Index(fields=['worker_id', 'date'], name='wages_recor_worker__7d8fae_idx')],
            },
        ),
    ]
