# Generated by Django 6.0.6 on 2026-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErpProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_code', models.CharField(max_length=50, unique=True)),
                ('process_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('standard_time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ERP工序数据',
                'verbose_name_plural': 'ERP工序数据',
                'db_table': 'erp_process',
            },
        ),
        migrations.CreateModel(
            name='ErpStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('bom', models.JSONField(blank=True, default=dict)),
                ('size_range', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('last_synced_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ERP款式数据',
                'verbose_name_plural': 'ERP款式数据',
                'db_table': 'erp_style',
            },
        ),
    ]
