# Generated by Django 6.0.6 on 2026-06-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_type', models.CharField(choices=[('style_development', '款式开发'), ('costing', '核工价审批'), ('techpack_review', '工艺单审核')], max_length=30)),
                ('object_id', models.IntegerField(help_text='关联业务对象ID')),
                ('title', models.CharField(max_length=200)),
                ('current_node', models.CharField(default='start', max_length=50)),
                ('status', models.CharField(choices=[('running', '进行中'), ('completed', '已完成'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='running', max_length=20)),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作流实例',
                'verbose_name_plural': '工作流实例',
                'db_table': 'workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=50)),
                ('handler', models.CharField(blank=True, help_text='处理人', max_length=100)),
                ('action', models.CharField(help_text='操作: approve/reject/submit/start', max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflowinstance')),
            ],
            options={
                'verbose_name': '工作流节点',
                'verbose_name_plural': '工作流节点',
                'db_table': 'workflow_node',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['workflow_type', 'status'], name='workflow_in_workflo_482d87_idx'),
        ),
    ]
