# Generated by Django 6.0.6 on 2026-06-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowinstance',
            options={'verbose_name': '工作流实例'},
        ),
        migrations.AlterModelOptions(
            name='workflownode',
            options={'ordering': ['created_at'], 'verbose_name': '工作流节点'},
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='action',
            field=models.CharField(help_text='approve/reject/submit/start', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='handler',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('initial', models.CharField(default='start', max_length=50)),
                ('nodes', models.JSONField(blank=True, default=list, help_text='节点列表')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_defs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作流定义',
                'db_table': 'workflow_definition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowdefinition'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uq_user_wf_name'),
        ),
    ]
