# Generated by Django 6.0.6 on 2026-06-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techpack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('process_name', models.CharField(max_length=100)),
                ('standard_time', models.DecimalField(decimal_places=2, help_text='标准工时(分钟)', max_digits=6)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='单件工费', max_digits=8)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '工序模板',
                'verbose_name_plural': '工序模板',
                'db_table': 'costing_process_template',
                'ordering': ['category', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CostingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('process_breakdown', models.JSONField(default=list)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('techpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costings', to='techpack.techpack')),
            ],
            options={
                'verbose_name': '核价结果',
                'verbose_name_plural': '核价结果',
                'db_table': 'costing_result',
            },
        ),
    ]
