# Generated by Django 6.0.6 on 2026-06-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('designer', '设计师'), ('pattern_maker', '版师'), ('accountant', '财务'), ('erp_sync', 'ERP同步账号')], default='designer', max_length=20)),
                ('avatar', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('erp_user_id', models.CharField(blank=True, help_text='ERP系统用户ID', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展',
                'verbose_name_plural': '用户扩展',
                'db_table': 'accounts_profile',
            },
        ),
    ]
