# Generated by Django 6.0.6 on 2026-06-26 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('tongyi', '阿里云通义千问')], default='openai', help_text='语言模型提供商', max_length=30)),
                ('llm_model', models.CharField(default='gpt-4o', help_text='语言模型名称', max_length=100)),
                ('image_provider', models.CharField(choices=[('sd_webui', 'Stable Diffusion WebUI'), ('tongyi_image', '通义万相')], default='sd_webui', help_text='图像生成模型提供商', max_length=30)),
                ('image_model', models.CharField(default='sd-xl', help_text='图像模型名称', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户AI配置',
                'verbose_name_plural': '用户AI配置',
                'db_table': 'accounts_user_ai_setting',
            },
        ),
    ]
