# Generated by Django 6.0.6 on 2026-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraisetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraisetting',
            name='image_api_key_enc',
            field=models.TextField(blank=True, help_text='图像模型 API Key（加密）'),
        ),
        migrations.AddField(
            model_name='useraisetting',
            name='llm_api_key_enc',
            field=models.TextField(blank=True, help_text='语言模型 API Key（加密）'),
        ),
        migrations.AlterField(
            model_name='useraisetting',
            name='image_model',
            field=models.CharField(default='sd-xl', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraisetting',
            name='image_provider',
            field=models.CharField(choices=[('sd_webui', 'Stable Diffusion WebUI'), ('tongyi_image', '通义万相')], default='sd_webui', max_length=30),
        ),
        migrations.AlterField(
            model_name='useraisetting',
            name='llm_model',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraisetting',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('tongyi', '阿里云通义千问')], default='openai', max_length=30),
        ),
    ]
