# Generated by Django 6.0.6 on 2026-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraisetting_image_api_key_enc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraisetting',
            name='image_api_base_url',
            field=models.CharField(blank=True, help_text='图像API地址，留空用默认', max_length=500),
        ),
        migrations.AddField(
            model_name='useraisetting',
            name='llm_api_base_url',
            field=models.CharField(blank=True, help_text='LLM API 地址，留空用默认', max_length=500),
        ),
    ]
