# Generated by Django 6.0.6 on 2026-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraisetting_image_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage_uuid',
            field=models.CharField(blank=True, help_text='用户文件存储目录UUID', max_length=16),
        ),
    ]
