# Generated by Django 6.0.6 on 2026-06-26 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('file_type', models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP'), ('gif', 'GIF')], max_length=20)),
                ('file_size', models.IntegerField(default=0, help_text='字节')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('model', '模特图'), ('garment', '服装图'), ('fabric', '面料图'), ('sketch', '设计稿'), ('moodboard', '灵感图'), ('other', '其他')], default='other', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '媒体素材',
                'verbose_name_plural': '媒体素材',
                'db_table': 'media_user_media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='media_user__user_id_ca6a11_idx')],
            },
        ),
    ]
