# Generated by Django 6.0.6 on 2026-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='file_url',
            field=models.TextField(help_text='图片URL（支持 base64 data URL）'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='thumbnail_url',
            field=models.TextField(blank=True),
        ),
    ]
